feat: Add Diff View component.
DXgovernance/DAVI pull request #181
Opened 2022-08-03 19:58 UTC by mprasanjith

# Description

Adds a diff view component to the action builder. The current implementation supports showing JSON diffs for the IPFS content hash update actions, but can be tweaked easily to support additional implementations.

A new `useIPFSFileMetadata` hook has also been implemented, which obtains the file size and mime type for an IPFS content-hash without downloading the content. It should be noted that this seems to be mostly undocumented although almost all gateways seem to support it.

Closes #11.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Tested locally using unit tests. Storybook was used for testing the UI.

# Checklist:

- [x] My code follows the existing style of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any UI changes have been tested and made responsive for mobile views

2022-08-04 06:16 UTC, Kenny-Gin1 reviewed
Nice! I will take a closer look a bit later. But what do you think about providing some screenshots of the end result?

Also, I think you have an integration test failing.

2022-08-04 06:16 UTC, Kenny-Gin1 commented on src/hooks/Guilds/ipfs/useIPFSFileMetadata.ts
> +    fetcher('https://cloudflare-ipfs.com/ipfs/' + hash),
Cool! Good use of `Promise.any`

2022-08-04 09:28 UTC, rossneilson commented
From my testing
![Screenshot 2022-08-04 at 10 25 50](https://user-images.githubusercontent.com/39137239/182813059-416846ce-246f-4a2b-b29b-55a57cbca787.jpg)

Its a little tough to test right now since we are not able to look up subdomains which is where json data would usually be stored
For now though functionality looks good, just going through code now

2022-08-04 10:28 UTC, rossneilson approved these changes

2022-08-05 09:33 UTC, Kenny-Gin1 submitted a review, later dismissed

2022-08-08 09:56 UTC, rossneilson requested changes
Some merge conflicts and I think pulling develop should fix your integration test

2022-08-08 14:37 UTC, rossneilson approved these changes

2022-08-09 12:58 UTC, rossneilson approved these changes

2022-08-09 13:12 UTC, merged