feat: Adding new abi and updating bytecodes
DXgovernance/DAVI pull request #212
Opened 2022-08-15 14:50 UTC by rossneilson

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Closes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

2022-08-16 09:59 UTC, Kenny-Gin1 requested changes
Looks good! You have some failing tests which I believe comes from us removing the `setPermissions` in our `ERC20Guild` contracts. It might also be that it got renamed to `setETHPermissions` in other cases.

And also please make sure to write a short summary and tick the checkboxes whenever your PR is ready for review. Otherwise, mark it as a draft if it is not ready yet.

2022-08-16 09:59 UTC, Kenny-Gin1 commented on src/Components/GuildSidebar/MemberInfoDropdown/MemberInfoDropdown.tsx
> +  console.log({ isRepGuild });
🧹 Remove `console.log`

2022-08-18 16:00 UTC, Filipv95 commented
@rossneilson Is there anything specific I should check in this PR? 'How to test' would be helpful also

2022-08-18 16:02 UTC, rossneilson commented
I think currently this is broken and I haven't managed to get back to it, let me mark as draft

2022-08-19 10:57 UTC, closed without merging