Display consistent params for generic calls
DXgovernance/DAVI pull request #275
Opened 2022-09-01 20:03 UTC by MiltonTulli

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. 

Closes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] My code follows the existing style of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any UI changes have been tested and made responsive for mobile views

2022-09-05 07:14 UTC, Filipv95 commented
@MiltonTulli Looks good to me.

2022-09-05 08:48 UTC, rossneilson commented
One failing test, looks like snapshots need updated

2022-09-05 17:15 UTC, MiltonTulli commented
> One failing test, looks like snapshots need updated

Fixed

2022-09-06 09:05 UTC, rossneilson commented
Hey, I think some slight misunderstanding here. The idea with the designs was to have a new section for this nice formatted section and then the user can still press the function name button to see the raw params. Let me know if you have more questions but my bad this wasn't clear. 
![Screenshot 2022-09-06 at 09 51 04](https://user-images.githubusercontent.com/39137239/188591547-03b89b22-d0fa-41d7-b784-8cb382d8e2b5.jpg)

2022-09-06 23:14 UTC, MiltonTulli commented
> Hey, I think some slight misunderstanding here. The idea with the designs was to have a new section for this nice formatted section and then the user can still press the function name button to see the raw params. Let me know if you have more questions but my bad this wasn't clear. ![Screenshot 2022-09-06 at 09 51 04](https://user-images.githubusercontent.com/39137239/188591547-03b89b22-d0fa-41d7-b784-8cb382d8e2b5.jpg)

@rossneilson This is ok for you? 
I think is a lot of information (approval + vest) but that was the way I found to make it readable. We could try putting approval section at the bottom or putting vest "intearct with" part at the top. Let me know what do you think. 
![Screen Shot 2022-09-06 at 19 59 26](https://user-images.githubusercontent.com/25844967/188756064-d1c7cd86-82e3-4094-8782-1a2a5a33ae62.png)

2022-09-07 16:10 UTC, rossneilson commented
> @rossneilson This is it ok for you? I think it is a lot of information (approval + vest) but that was the way I found to make it readable. We could try putting approval section at the bottom or putting vest "intearct with" part at the top. Let me know what you think. ![Screen Shot 2022-09-06 at 19 59 26](https://user-images.githubusercontent.com/25844967/188756064-d1c7cd86-82e3-4094-8782-1a2a5a33ae62.png)

Hmmm, it will be a lot of information on the spending call ones. I think putting `Interact with X` -> `All readable params` -> `function button` -> Repeat for next call.
Not sure if this makes sense, if not we can jump on a call.

2022-09-09 17:12 UTC, Filipv95 commented
@MiltonTulli Looks good to me, great job!

2022-09-09 17:47 UTC, rossneilson commented
It would be nice to have this behaviour similar across all of our action types, just testing it seems like transfer doesn't have the same behaviour as generic calls

2022-09-09 18:28 UTC, MiltonTulli commented
> It would be nice to have this behaviour similar across all of our action types, just testing it seems like transfer doesn't have the same behaviour as generic calls

Sounds good! Since this task had several changes after I started working on it I would prefer to create new issues for all action types also to avoid making this larger.

2022-09-12 12:09 UTC, dcrescimbeni requested changes

2022-09-12 14:52 UTC, MiltonTulli commented on src/locales/en/translation.json
> -  },
Very weird, i don't remember me removing this. Thanks for bringing this up. 
I restored ipfs translations. Btw I think we are not using `failedToUpload` and `couldntUploadToPinata` keys.

2022-09-12 15:30 UTC, dcrescimbeni approved these changes

2022-09-12 16:26 UTC, merged